// Devils Inc Studios
// Copyright DEVILS INC. STUDIOS LIMITED 2014, 2015
//
// TODO: Include a description of the file here.
//

public enum Items
{
	AMMO_LASER_SHOT,
	AMMO_TRACKING_SHOT,
	AMMO_SHOCKWAVE,
	AMMO_DRONE,
	DEBUFF_SPEED,
	DEBUFF_FUEL,
	DEBUFF_BACKWARDS_CONTROLS,
	DEBUFF_SHIELD,
	DEBUFF_WEAPON_TARGETING,
	DEBUFF_WARP,
	ITEM_SHIELD_REPAIR,
	ITEM_HULL_REPAIR,
	POWERUP_INVINCIBILITY,
	POWERUP_MULTISHOT,
	POWERUP_UNLIMTED_AMMO,
	POWERUP_DRONE_SWARM,
	POWERUP_QUAD_DAMAGE,
	POWERUP_REVIVE_TEAMMATE,
	POWERUP_MULIPLIER_UP,
}