// Devils Inc Studios
// Copyright DEVILS INC. STUDIOS LIMITED 2014, 2015
//
// TODO: Include a description of the file here.
//

public enum Enemies
{
	ASTEROID,
	ENEMY_TRACKER,
	ENEMY_FIGHTER_LIGHT,
	ENEMY_FIGHTER_HEAVY,
	ENEMY_FIGHTER_MEDIUM,
	ENEMY_INTERCEPTOR,
	ENEMY_BOMBER,
	ENEMY_CRUSIER,
	ENEMY_BOSS,
}