// Devils Inc Studios
// Copyright DEVILS INC. STUDIOS LIMITED 2014
//
// TODO: Include a description of the file here.
//
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Cooldown Timer")]
public class CooldownTimer : MonoBehaviour
{
	[Header("Cooldown Settings")]
	public float cooldownMax = 1.0f;
	public float cooldownLeft = 0.0f;
	public float cooldownProgress = 0.0f;
	public Image cooldownImage;
	public WeaponType weapon;

	//[Header("Reference Settings")]
//	public FPSShooting fpsShooting;

	public void OnEnable()
	{
	//	if (shotDelayTimers[(int)playerState.getSelectedWeapon()] <= 0.0f) {
//		switch (weapon) {
//		case WeaponType.MAIN_GUN:
//		case WeaponType.LASER_SHOT:
//		case WeaponType.SHOCKWAVE:
//		case WeaponType.TRACKING_SHOT:
//		case WeaponType.DRONE:
//			cooldownMax = PrefabLoader.instance.getPrefab(weapon.ToString()).GetComponent<ProjectileController>().shotDelay;
//			break;
//		}
	}

	public void Update()
	{
		//cooldownLeft = fpsShooting.shotDelayTimers[(int)weapon];
		//cooldownProgress = cooldownLeft / cooldownMax;
		//cooldownImage.fillAmount = cooldownProgress;
	}
}
